//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AnswerSheet
    {
        public string MemberId { get; set; }
        public int QuestionId { get; set; }
        public int QuestionOrder { get; set; }
        public int ExamId { get; set; }
        public int TestNo { get; set; }
        public Nullable<int> ChoiceId { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> TimeUsed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateedDate { get; set; }
        public string ChoiceType { get; set; }
        public Nullable<int> FakeChoiceId { get; set; }
    }
}
