//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ChoiceWG
    {
        public int ChoiceId { get; set; }
        public int QuestionId { get; set; }
        public string ChoiceNameTH { get; set; }
        public string ChoiceNameEN { get; set; }
        public int Point { get; set; }
        public string ChoiceType { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
