//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ExamStat
    {
        public string MemberId { get; set; }
        public int TestNo { get; set; }
        public int ExamId { get; set; }
        public Nullable<decimal> ScoreSet { get; set; }
        public Nullable<decimal> ScoreGet { get; set; }
        public Nullable<int> TimeUsed { get; set; }
        public Nullable<int> TimeSet { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string TestStatus { get; set; }
        public Nullable<int> ExamAccessTimes { get; set; }
    }
}
