//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Exam
    {
        public int ExamId { get; set; }
        public string PrefixName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public string ExamDesc { get; set; }
        public System.DateTime AddDate { get; set; }
        public string ExamStatus { get; set; }
        public Nullable<int> Remind1 { get; set; }
        public Nullable<int> Remind2 { get; set; }
    }
}
