//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FakeChoice
    {
        public int FakeChoiceId { get; set; }
        public string FakeChoiceNameTH { get; set; }
        public string FakeChoiceNameEN { get; set; }
        public string FakeChoiceType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Point { get; set; }
    }
}
