//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Member
    {
        public string MemberId { get; set; }
        public string MemberNameTH { get; set; }
        public string MemberLastNameTH { get; set; }
        public string MemberNameEN { get; set; }
        public string MemberLastNameEN { get; set; }
        public Nullable<System.DateTime> MemberDOB { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public int Status { get; set; }
        public string Role { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public int FailLogin { get; set; }
    }
}
