//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Question
    {
        public int QuestionId { get; set; }
        public Nullable<int> FactorId { get; set; }
        public Nullable<int> SubFactorId { get; set; }
        public string DataTH { get; set; }
        public string DataEN { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string QuestionStatus { get; set; }
        public string UpdatedBy { get; set; }
    }
}
