//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritProject.DBUtils
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SubFactor
    {
        public int SubFactorId { get; set; }
        public int FactorId { get; set; }
        public string SubFactorNameTH { get; set; }
        public string SubFactorNameEN { get; set; }
    }
}
