//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string btn_BeginExam {
            get {
                return ResourceManager.GetString("btn_BeginExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btn_Confirm {
            get {
                return ResourceManager.GetString("btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Page.
        /// </summary>
        internal static string btn_Home {
            get {
                return ResourceManager.GetString("btn_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btn_Next {
            get {
                return ResourceManager.GetString("btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btn_Submit {
            get {
                return ResourceManager.GetString("btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string btn_Unlock {
            get {
                return ResourceManager.GetString("btn_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string field_Email {
            get {
                return ResourceManager.GetString("field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string field_Password {
            get {
                return ResourceManager.GetString("field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string field_RePassword {
            get {
                return ResourceManager.GetString("field_RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string field_Username {
            get {
                return ResourceManager.GetString("field_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Times.
        /// </summary>
        internal static string lbl_AccessTimes {
            get {
                return ResourceManager.GetString("lbl_AccessTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Config.
        /// </summary>
        internal static string lbl_AdminConfig {
            get {
                return ResourceManager.GetString("lbl_AdminConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin List.
        /// </summary>
        internal static string lbl_AdminList {
            get {
                return ResourceManager.GetString("lbl_AdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Name.
        /// </summary>
        internal static string lbl_AdminName {
            get {
                return ResourceManager.GetString("lbl_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Registration.
        /// </summary>
        internal static string lbl_AdminRegister {
            get {
                return ResourceManager.GetString("lbl_AdminRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner Report List.
        /// </summary>
        internal static string lbl_AdminReportList {
            get {
                return ResourceManager.GetString("lbl_AdminReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string lbl_Choice {
            get {
                return ResourceManager.GetString("lbl_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language to start..
        /// </summary>
        internal static string lbl_chooseLang {
            get {
                return ResourceManager.GetString("lbl_chooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen ID.
        /// </summary>
        internal static string lbl_CitizenId {
            get {
                return ResourceManager.GetString("lbl_CitizenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string lbl_Complete {
            get {
                return ResourceManager.GetString("lbl_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished date and time.
        /// </summary>
        internal static string lbl_CompleteData {
            get {
                return ResourceManager.GetString("lbl_CompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ?.
        /// </summary>
        internal static string lbl_ConfirmBox {
            get {
                return ResourceManager.GetString("lbl_ConfirmBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner List.
        /// </summary>
        internal static string lbl_ExaminerList {
            get {
                return ResourceManager.GetString("lbl_ExaminerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string lbl_ExamIntro {
            get {
                return ResourceManager.GetString("lbl_ExamIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        internal static string lbl_ExamName {
            get {
                return ResourceManager.GetString("lbl_ExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string lbl_Factor {
            get {
                return ResourceManager.GetString("lbl_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor English.
        /// </summary>
        internal static string lbl_FactorEN {
            get {
                return ResourceManager.GetString("lbl_FactorEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Thai.
        /// </summary>
        internal static string lbl_FactorTH {
            get {
                return ResourceManager.GetString("lbl_FactorTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Administrator.
        /// </summary>
        internal static string lbl_forAdmin {
            get {
                return ResourceManager.GetString("lbl_forAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lbl_From {
            get {
                return ResourceManager.GetString("lbl_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_FullName {
            get {
                return ResourceManager.GetString("lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Overview.
        /// </summary>
        internal static string lbl_Graph1 {
            get {
                return ResourceManager.GetString("lbl_Graph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score by Factors.
        /// </summary>
        internal static string lbl_Graph2 {
            get {
                return ResourceManager.GetString("lbl_Graph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        internal static string lbl_hello {
            get {
                return ResourceManager.GetString("lbl_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string lbl_Id {
            get {
                return ResourceManager.GetString("lbl_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastAccess.
        /// </summary>
        internal static string lbl_LastAccess {
            get {
                return ResourceManager.GetString("lbl_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string lbl_LastName {
            get {
                return ResourceManager.GetString("lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string lbl_Level {
            get {
                return ResourceManager.GetString("lbl_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Score.
        /// </summary>
        internal static string lbl_Mean {
            get {
                return ResourceManager.GetString("lbl_Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ENG]ผลสรุปแยกด้าน.
        /// </summary>
        internal static string lbl_Mean2 {
            get {
                return ResourceManager.GetString("lbl_Mean2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ENG]คำแปล.
        /// </summary>
        internal static string lbl_Mean3 {
            get {
                return ResourceManager.GetString("lbl_Mean3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string lbl_Minute {
            get {
                return ResourceManager.GetString("lbl_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string lbl_Mr {
            get {
                return ResourceManager.GetString("lbl_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string lbl_Mrs {
            get {
                return ResourceManager.GetString("lbl_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string lbl_Ms {
            get {
                return ResourceManager.GetString("lbl_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Admin.
        /// </summary>
        internal static string lbl_NewAdmin {
            get {
                return ResourceManager.GetString("lbl_NewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norm.
        /// </summary>
        internal static string lbl_Norm {
            get {
                return ResourceManager.GetString("lbl_Norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string lbl_Of {
            get {
                return ResourceManager.GetString("lbl_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string lbl_PortDone {
            get {
                return ResourceManager.GetString("lbl_PortDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lbl_PortTotal {
            get {
                return ResourceManager.GetString("lbl_PortTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportion of Test Item Done.
        /// </summary>
        internal static string lbl_Proportion {
            get {
                return ResourceManager.GetString("lbl_Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string lbl_Question {
            get {
                return ResourceManager.GetString("lbl_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lbl_QuestionEnglish {
            get {
                return ResourceManager.GetString("lbl_QuestionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string lbl_QuestionThai {
            get {
                return ResourceManager.GetString("lbl_QuestionThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question List.
        /// </summary>
        internal static string lbl_QuestionView {
            get {
                return ResourceManager.GetString("lbl_QuestionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Date.
        /// </summary>
        internal static string lbl_RecentDate {
            get {
                return ResourceManager.GetString("lbl_RecentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string lbl_Report {
            get {
                return ResourceManager.GetString("lbl_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Summary.
        /// </summary>
        internal static string lbl_ResultScore {
            get {
                return ResourceManager.GetString("lbl_ResultScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfactor English.
        /// </summary>
        internal static string lbl_SubfactorEN {
            get {
                return ResourceManager.GetString("lbl_SubfactorEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfactor Thai.
        /// </summary>
        internal static string lbl_SubfactorTH {
            get {
                return ResourceManager.GetString("lbl_SubfactorTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ENG]ขณะนี้คุณได้ทำข้อสอบชุด.
        /// </summary>
        internal static string lbl_Summary1 {
            get {
                return ResourceManager.GetString("lbl_Summary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ENG]เสร็จสิ้นเเล้ว.
        /// </summary>
        internal static string lbl_Summary2 {
            get {
                return ResourceManager.GetString("lbl_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have done this survey. Thank you for your time..
        /// </summary>
        internal static string lbl_Summary3 {
            get {
                return ResourceManager.GetString("lbl_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of this survey show that you are the type of person.
        /// </summary>
        internal static string lbl_Summary4 {
            get {
                return ResourceManager.GetString("lbl_Summary4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        internal static string lbl_TestDate {
            get {
                return ResourceManager.GetString("lbl_TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string lbl_TestTimes {
            get {
                return ResourceManager.GetString("lbl_TestTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Left.
        /// </summary>
        internal static string lbl_TimeLeft {
            get {
                return ResourceManager.GetString("lbl_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string lbl_Times {
            get {
                return ResourceManager.GetString("lbl_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent (Min).
        /// </summary>
        internal static string lbl_TimeSpent {
            get {
                return ResourceManager.GetString("lbl_TimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Used.
        /// </summary>
        internal static string lbl_TimeUesd {
            get {
                return ResourceManager.GetString("lbl_TimeUesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total question answered.
        /// </summary>
        internal static string lbl_Total {
            get {
                return ResourceManager.GetString("lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string lbl_Unit {
            get {
                return ResourceManager.GetString("lbl_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Member ?.
        /// </summary>
        internal static string lbl_UnlockMember {
            get {
                return ResourceManager.GetString("lbl_UnlockMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string lbl_UpdatedDate {
            get {
                return ResourceManager.GetString("lbl_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lbl_Username {
            get {
                return ResourceManager.GetString("lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string lbl_Version {
            get {
                return ResourceManager.GetString("lbl_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to  PTT Personality Assessment.
        /// </summary>
        internal static string lbl_welcome {
            get {
                return ResourceManager.GetString("lbl_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score.
        /// </summary>
        internal static string lbl_YourScore {
            get {
                return ResourceManager.GetString("lbl_YourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score &lt; Norm.
        /// </summary>
        internal static string lbl_YourScoreBad {
            get {
                return ResourceManager.GetString("lbl_YourScoreBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score &gt;= Norm.
        /// </summary>
        internal static string lbl_YourScoreGood {
            get {
                return ResourceManager.GetString("lbl_YourScoreGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string menu_Analytics {
            get {
                return ResourceManager.GetString("menu_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string menu_Config {
            get {
                return ResourceManager.GetString("menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examiner List.
        /// </summary>
        internal static string menu_ExaminerList {
            get {
                return ResourceManager.GetString("menu_ExaminerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menu_Home {
            get {
                return ResourceManager.GetString("menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string menu_logOut {
            get {
                return ResourceManager.GetString("menu_logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Admin.
        /// </summary>
        internal static string menu_NewAdmin {
            get {
                return ResourceManager.GetString("menu_NewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Review.
        /// </summary>
        internal static string menu_QuestionReview {
            get {
                return ResourceManager.GetString("menu_QuestionReview", resourceCulture);
            }
        }
    }
}
